### PR TITLE
Added Ecoining pool guide

### PR DESCRIPTION
**Pull request by mrbickle**
```
new file:   img/mining7.png Ecoining Pool Image
new file:   img/mining8.png Ecoining Pool Image
new file:   img/mining9.png Ecoining Pool Image
modified:   mining.php Added Ecoining pool guide & resources & wallet guide link
```

### CODE REVIEW

**Comment by mrbickle** [comment]
Hello, I've added an Ecoining pool mining guide in the mine section. Also added a link to the resources and one to the wallet install guide.

Modify it as you please or tell me if there's something to change :)

Thanks for your work!!

**Comment by super3** [comment]
D7 seems to be one of the largest pools. I'm not going to giving Ecoining any priority over the the existing article. 

If you would like to follow the format of Minting then perhaps I might accept the pull. In the future, I think we will resolve priority with sponsorships.

**Comment by mrbickle** [comment]
Hello Shawn, I don't understand the reasons you closed the pull request. I don't mean to argue the decision, as to understand the reasons.
What do you mean following the format of Minting? We tried to follow it adding the green accordion that unfolds the info.

Also don't understand the priority thing... Is because I put Ecoining over D7? If that's the problem I can just change it, as I told you.

I even thought about adding the info from resources page and guides for the other pools too as I think it's the correct place and  it is in fact healthy for the Peercoin network trying to distribute the hash, as some people discussed in the forum.

Thanks for your time.

**Comment by super3** [comment]
I spent maybe 10 seconds reading the diff. Thought you just replaced it. I'll reopen and take a look later.

**Comment by mrbickle** [comment]
Thanks!

You can check our website test version to see the result here:
http://107.170.28.107/perc/mining.php

**Comment by super3** [comment]
Footer is broken. Are you missing a Div?

**Comment by mrbickle** [comment]
True! Added missing div and now the footer is fixed.

**Comment by super3** [comment]
Please squash commits, or open a new pull.

**Pull request closed without merging**
