### PR TITLE
Fixed several grammatical issues

### PR DESCRIPTION
**Pull request by Gnewt**
Standardized the usage of "proof-of-work/proof-of-stake" gramatically on the FAQ. In the FAQ, those two terms are always hyphenated and also separated by a slash when mentioned together. Also added spaces in several locations lacking them after the end of words (between both parentheses and periods).

### CODE REVIEW

**Comment by super3** [comment]
I believe Proof-of-work+Proof-of-stake is more accurate but it looks kinda weird formatted. What do you guys think? @Sentinelrv @iheartcryptocoin

**Comment by Gnewt** [comment]
I think "Proof-of-work+Proof-of-stake" looks pretty bad written out, but happy to change it to whatever. "Slash" does not imply "or" in my mind.

**Comment by super3** [comment]
Yeah you are right. Squash and I'll merge it.

**Comment by Gnewt** [comment]
Squashed!

**Comment by super3** [comment]
Squashed

**Pull request merged**
