### PR TITLE
Added total supply to data culled from CoinMarketCap

### PR DESCRIPTION
**Pull request by Gnewt**
Also changed the permissions of the SQLite3 database to 777. This isn't great security practice, but the data held in that DB is not particularly sensitive -- this makes sense for now.

### CODE REVIEW

**Comment by Gnewt** [comment]
I changed the SQLite perms to 777 but it looks like Git may have only recognized up to 755.

**Comment by Gnewt** [comment]
It lives!

**Comment by super3** [comment]
Your awesome dude. Do you think you can write the PHP or Javascript call for index.php? It doesn't have to be pretty. @jvanoel will take care of making it look nice.

**Comment by Gnewt** [comment]
Yeah definitely. Would you prefer a direct PHP include or a JavaScript call? I lean toward JavaScript call just for asynchronicity's sake.

Our current update interval on the backend is 30 seconds, so I'll commit code that updates every 30 seconds. We can update that as needed. I'll have the "update" function grab the data, update it on the page, and then set a timeout so it runs again in 30 seconds.

**Comment by super3** [comment]
JS is fine. Your reasoning is sound. In the future, I'll just use 'ACK' for acknowledgement. No need for me to micro-manage. Just go with your gut, and I'll only jump in when I disagree. 

So, ACK.

**Pull request merged**
