### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by iheartcryptocoin**

### CODE REVIEW

**Comment by Sentinelrv** [comment]
About the comma in "it's." I meant to say it doesn't need an apostrophe.

**Comment by iheartcryptocoin** [comment]
•In the intro text, algorithm is plural. Are you referring to both pow and pos here? 
-- artifact from pasting

•At the end of the intro text and at the end of the Features text there are missing periods.
-- fixed

•Throughout the text, the word cryptocurrency is either one word or split into two words. We should be consistent with our wording. 
--one word 

•Similarly, sometimes proof-of-stake and proof-of-work are capitalized and sometimes they're not. 
-- lowercase

•"Peercoin is a more advanced cryptocurrency." Than what? Should we point out Bitcoin here? 
-- no, singling out bitcoin leaves door open for other contenders.  stronger position is to tout own strengths and leave to other to prove wrong

•Under the features text you have this: "Through it's innovative...." Its doesn't need an apostrophe because it shouldn't be a contraction. 
-- yep, fixed this several times while making changes, was make a copy paste error somewhere and bringing it back in lol  too tired....

•I believe market cap is two words, not one. 
-- yes, shouldn't abbreviate anyway

•Check the spacing between sentences. Some have too many spaces or too little. 
-- fixed

•Under the proof-of-stake section, the second "algorithm is spelled wrong. It says "algothrithm." 

-- good catch

**Comment by super3** [comment]
cryptocurrency title is misspelled. 
original innovation, and increased security are way too long. cut them in half. if we really need to explain we can do that further down.

**Comment by iheartcryptocoin** [comment]
In my original edit I planned for shorter feature desc with a "read more" link to follow. But haven't had time to find the original discussions/presentations of these topics or write something from scratch.  Absent those links it is relatively better to include info on the page fore now.

As a final more ideal solution do you know where original discussions or presentations are?  If so can you save me the time of searching fresh and then can cut down text link based on what thee read more links actually link to.  Otherwise will work on fuller descriptions in original text as a next step

**Comment by super3** [comment]
I think 4da394e might have broken the CSS. @Sentinelrv Can you help with that?

**Comment by super3** [comment]
Fix the header, and cut the text then lets get this merged.

**Comment by iheartcryptocoin** [comment]
What font is the peercoin logo originally done in?

**Comment by iheartcryptocoin** [comment]
Added the readmore JQ JS

If we can change the tagline to the peercoin original logo font should be good to go

**Comment by Sentinelrv** [comment]
The font is Myriad Pro, the same font Apple uses.

**Comment by super3** [comment]
Logo text is broken.

**Comment by iheartcryptocoin** [comment]
yes it is, still trying to figure out how to upload image file through this website interface

**Comment by super3** [comment]
Are you using Windows?

**Comment by iheartcryptocoin** [comment]
yes Win8

**Comment by super3** [comment]
use the desktop github for windows client

**Comment by iheartcryptocoin** [comment]
Tried installing Github for windows EXE and getting error "application cannot be started" googled and didn't find a solution that works to get around this

**Comment by iheartcryptocoin** [comment]
yeah already tried to get that man, see above comment

**Comment by super3** [comment]
Email me the file. I'll commit it to your repo.

**Comment by iheartcryptocoin** [comment]
Yeah that's not a sustainable, but we can go with the ducttape and bubblegum solution for now haha.  

I'll dig into this error further or see if I can get my hands on a box to run Linux later on.   Email sent

**Comment by iheartcryptocoin** [comment]
Brilliant, did you have any issues with the JS I added?

**Comment by super3** [comment]
Is there supposed to be a 'see more' button because I just see the full text.

**Comment by iheartcryptocoin** [comment]
I created and committed the js files.  I wonder if they were deleted when I merged in your image pull.  Just recreated again

**Comment by super3** [comment]
Need to teach you how to squash, but ACK on megamerge.

**Pull request merged**
