### PR TITLE
screenshots

### PR DESCRIPTION
**Pull request by ngbatnicdotmil**
I changed the style of screenshots,so the dummies could get it

ps

I'll make the minting today, or a liitle later, tomorrow

### CODE REVIEW

**Comment by super3** [comment]
Looks better. Let me know when you added minting.

**Comment by ngbatnicdotmil** [comment]
minting is already done )))

Date: Sun, 5 Jan 2014 10:18:46 -0800

**Comment by super3** [comment]
Great work. Much more readable.

**Comment by ngbatnicdotmil** [comment]
thanks ))

Date: Sun, 5 Jan 2014 11:28:37 -0800

**Comment by super3** [comment]
Can you tackle this next?
https://github.com/super3/Peercoin.net/issues/108

**Comment by ngbatnicdotmil** [comment]
I'll try to do my best ))

Date: Sun, 5 Jan 2014 11:30:40 -0800

**Comment by super3** [comment]
Jesus. Looks like you just got paid per commit. Merging is now required.

**Comment by ngbatnicdotmil** [comment]
sorry?

Date: Sun, 5 Jan 2014 11:50:48 -0800

**Comment by super3** [comment]
Nah its good. Lesson learned.

**Comment by ngbatnicdotmil** [comment]
"By seeking and blundering we learn." ¯ Johann Wolfgang von Goethe

Date: Sun, 5 Jan 2014 11:52:31 -0800

**Pull request merged**
