### PR TITLE
Update minting.php

### PR DESCRIPTION
**Pull request by sandakersmann**
Corrected some typos

### CODE REVIEW

**Comment by sandakersmann** [comment]
Don't know how to put these pull requests in one, but if you watch my bitcoin address you can see that I have donated more to the project than I have received in tips. I will donate back whatever I receive.

**Comment by Gnewt** [comment]
Learn how to use [Interactive rebase](https://help.github.com/articles/interactive-rebase), all you have to do is change "pick" to "squash" for all but 1 commit. Let me know if you need help!

**Comment by Gnewt** [comment]
If you're in a terminal: git rebase -i

**Comment by sandakersmann** [comment]
I don't understand how to do this. As i said I have donated 0.06 BTC and received 0.01933844 BTC in tips for one commit. You can check this here: http://tip4commit.com/projects/222/tips

I will donate back whatever I receive for these 4 pull requests.

**Comment by sandakersmann** [comment]
I can send 0.08 BTC first if you say that all 4 pull requests will be merged.

**Comment by super3** [comment]
https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by sandakersmann** [comment]
Will you merge all 4 if I send 0.08 BTC to the project (1HzRcds2rubVbSfXAvGS43fuEoeGzaH4g4)?

**Comment by super3** [comment]
@sandakersmann I'd rather you learn how to use git. I know its hard, but its good for you. Also makes for a cleaner repo.

**Comment by sandakersmann** [comment]
Sorry. Don't have time for this. Do whatever you want. I will send the tips back if you merge.

**Pull request closed without merging**
