### PR TITLE
Update strings.php with Dutch translations

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Fixed

**Comment by mark-bl** [comment]
You need to change locale/languages.php and add Dutch to there
the fix should be adding:
'nl'    =>      'Dutch',

without that, Dutch won't appear as an option.
also, squash the commits after that please.

**Comment by ghost** [comment]
Thanks, fixed and rebased commits.

**Comment by danbartram** [comment]
Thanks for the translations, @lazlolazlolazlo.

I don't know if @super3 wants translations pulled in just yet, because of a possible content overhaul soon anyway. Hopefully your work can be added.

One little thing: The `languages.php` file takes a country code (ISO 639-1) as the key (such as "NL"), and the value is the native translation of that language.

What I mean is that "French" is not "French", but "Français" - how it's native language writes it.

In your case, "Dutch" should be "Nederlands".

**Comment by ghost** [comment]
Fixed and rebased

**Comment by super3** [comment]
Can't merge.

**Pull request closed without merging**
