### PR TITLE
Create price and market cap JSON backend

### PR DESCRIPTION
**Pull request by Gnewt**
Add a tickerinfo.php that returns current price and market cap in JSON format. Caches data in SQLite3 for a period to avoid hammering CoinMarketCap servers.

### CODE REVIEW

**Comment by Gnewt** [comment]
Make sure the sqlite3 database is writeable serverside

**Comment by super3** [comment]
I'm currently just flailing at the keyboard to try to make this work. That might just be the case. Let me try to remember the unix command for that.

**Comment by Gnewt** [comment]
The brute-force approach is "chmod 777 ppcmarket.sqlite3" but the proper method would be to chown to full ownership by www-data ("chown www-data:www-data ppcmarket.sqlite3") (or whichever other user runs PHP, it's not always www-data). Let me know if I can help.

**Comment by super3** [comment]
Yeah I took the brute force approach and did that. Anything else I need to do to make it start magically working?

**Comment by Gnewt** [comment]
It's possible the version of PHP running on the server is incompatible with something in the code. Could you tail the PHP error logs? Or even try running it directly from CLI with 'php tickerinfo.php'? I just ran it from CLI on my local copy of the repo and it output "{"price":5.96,"market_cap":125295192}" just fine.

**Comment by super3** [comment]
```
 PHP Fatal error:  Class 'SQLite3' not found in /var/www/tickerinfo.php on line 55
```

I think I'm just missing php5-sqlite let me apt-get that, restart apache, and try again.

**Comment by Gnewt** [comment]
Oops -- that'd do it. That should solve the issue though.
EDIT: Looks like it did!

**Comment by super3** [comment]
It's alive! http://peercoin.net/tickerinfo.php
Do you might throwing in total supply for good measure?

**Comment by Gnewt** [comment]
Sure, one sec.

**Comment by Gnewt** [comment]
Er, more than one sec -- it doesn't have an ID so I'll have to play with the ordering. I'll get it done soon.

**Pull request merged**
