### PR TITLE
Implemented basic locale system with English translations

### PR DESCRIPTION
**Pull request by danbartram**
## Usage

All of the translations/localized strings are stored in `locale/strings.php` in the following format:

``` php
$locale_strings['en']['market_cap'] = "Market Cap";

// "en" as the two digit language code
// "market_cap" as the text id
// "Market Cap" as the written language version
```

To output the translation/locale version of some text, initialize the `Locale` class and call the `getText()` method, like so:

``` php
<?php echo $Locale->getText("market_cap"); ?>
```
### Available Languages

Available languages should be added to the `locale/languages.php` file along with their two digit language code, and their native translation.

For example:

``` php
$locale_languages = array(
        'en'    =>  'English',
        'es'    =>  'Español',
        'fr'    =>  'Français',
    );
```

Once added to the available languages file, they'll instantly get added to the language selection bar (currently only added in the footer).
### How does it know when to translate?

You can trigger the use of a specific locale language by visiting a URL with the GET parameter set for `?locale=fr`, which will force the `Locale` class to set a cookie named `locale` and reference later.

If neither a cookie or a GET parameter are supplied, the browser's `Accept-Language` header value is used.
### Language Bar - Footer

This is how the current language bar looks in this commit, because of the responsive design issue explained below there isn't a top bar added yet. If you can add one, that'd be great.
Language Bar
### Issues
- I've not been able to properly place the language bar at the top of the page. I can get it looking right at desktop resolution, but not responsively. I don't want to make the CSS cluttered and "hacky" by adding a lot of media queries unless necessary.
- There are no translations for other languages yet, and I've only done incredibly basic translation examples to illustrate how it works, i.e. the big header text has been translated into Spanish and French.
- The usage of: `php $_SERVER['PHP_SELF'];` might have a problem with the `.htaccess` rules we set up earlier as it's pointing to a .php file. If that happens, we can simply change it to "/" for now as you only want to affect the index page anyway.

### CODE REVIEW

**Comment by super3** [comment]
I've never seen a pull req this beautiful in my repo. Can we verify that we don't break things with the .htaccess? You can test it or I can do a production test when I'm sitting at the computer.

**Comment by danbartram** [comment]
Thank you very much!

The `.htaccess` issue isn't really an issue _right now_ because there's no `.htaccess` RewriteRule for `index.php`.

I mentioned it because we need to check on it when we implement a site-wide locale system, incase the RewriteRules interfere and strip `_GET` parameters. On my system it works great and it's not an issue. I'm just saying there may be a config conflict between our systems.

Anyway, as of right now, it works 100% fine on my end, `.htaccess` rules and all are not an issue.

**Comment by super3** [comment]
Ok. I'll pull it in a few hours and see what happens.

**Comment by super3** [comment]
Resulted in a blank page. Had to revert. I'm going to launch server for development, and testing. I keep on breaking the website in production.

**Comment by danbartram** [comment]
Strange. It's fine my end. Sounds like there's an error being suppressed and so you're getting a blank page.

That'd be worth checking to see if there's an issue my server doesn't mind working through.

I'm testing on Apache 2.4 with PHP 5.4.7.

Edit: Tested on a different VM with Apache 2.2.22 and PHP 5.3.10-1ubuntu3.7 - still works fine my end.

Can you post your error logs?

**Comment by danbartram** [comment]
Peercoin.net is running on PHP/5.4.4-14+deb7u7 so I updated my VM's PHP version to 5.4.25 incase the .4 bump was causing syntax issues, but it still works great.

I still don't know why it didn't work on your end?

Is the deploy script lacking in permissions? Is it not creating the new directory `locale`?

That's the other thing I can think of that may be the issue. Maybe the deploy script doesn't have permission to create a new directory, only modify the current files, and so PHP is throwing a fatal error because the `Locale` class is missing?

**Comment by super3** [comment]
Sure I set permissions on deploy script or it would not be able to modify
/var/www I'll double check on that.

If that doesn't work can you provide me with ssh public key and I can have
you poke around on a clone of the server yourself?

**Comment by danbartram** [comment]
Sure, and I only mentioned it because I'm sure I had permission issues like that before. I could modify files and everything else, but I couldn't create new directories, wondered if that was the case again here.

**Comment by super3** [comment]
Don't want this to get buried. Can you open a new issue and reference this?

**Comment by danbartram** [comment]
Created issue #246.

**Pull request merged**
