### PR TITLE
Added 301 redirects and updated README with extra deployment info

### PR DESCRIPTION
**Pull request by danbartram**
Tested my end and it still works fine, let's hope the MultiViews doesn't come to haunt this commit.

### CODE REVIEW

**Comment by super3** [comment]
Much commit. Very pull. Wow.

**Comment by danbartram** [comment]
So test.

[waiting intensifies]

**Comment by super3** [comment]
Redirect loop happened. Reverted.
Add the README back, and lets call it a day. We have tempted the coding
gods too much today.

On Fri, Feb 21, 2014 at 2:49 PM, Dan Bartram notifications@github.comwrote:

> So test.
> 
> [waiting intensifies]
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/super3/peercoin.net/pull/239#issuecomment-35766329
> .

## 

Shawn Wilkinson
Bitcoin Developer/Entrepreneur/Enthusiast
(1P4QkLsujBPBZyUwDezikL4fUSs7JvFhPv)
me@super3.org
http://super3.org

**Comment by danbartram** [comment]
Eurgh, damnit.

I think we could work around it if we implemented a PHP router or something, but that may be overkill - that's up to you to decide.

I'll re-send the README update now.

**Pull request merged**
