### PR TITLE
Language/Style updates

### PR DESCRIPTION
**Pull request by xeroc**
- added exchange 'more' with link
- removed (Beta) from paper wallet
- renamed wallet generator to paper wallet!

index.php:
- changed link to funding addresses ... please give some hint on the
  validity of those addresses
- Installing and setting up "the" Wallet
- More resources
- social networks

### CODE REVIEW

**Comment by super3** [comment]
Can't automerge.

**Comment by xeroc** [comment]
Whats the issue with merging? Did i made a mistake somewhere?

**Comment by super3** [comment]
Something was pulled into the repository after this commit was made, and something conflicts. I don't know what it is.

**Comment by xeroc** [comment]
Ok ... So i fixed the commit

It's been due to the removing of *.php in the urls

Hope it works for you now!

**Comment by super3** [comment]
please squash or create a new pull req

**Comment by xeroc** [comment]
Please close this pull request .. latest pulls changed too much for that to be squashed

**Comment by super3** [comment]
Please open new pull req.

**Pull request closed without merging**
