### PR TITLE
Added MIT license to downloads page, fixes #167

### LINKED ISSUE #167: Add Terms of Service
Terms of Service (TOS) or End User License Agreement (EULA.) Ideally the EULA would be right next to every download button.

### PR DESCRIPTION
**Pull request by Gnewt**

### CODE REVIEW

**Comment by Gnewt** [comment]
@super3 can you look this over? It's fine to merge, just want an opinion about its placement. I just copied the MIT license from the ppcoin repo, which I think is fitting. Right now the text is simply placed under the download buttons on the Downloads page.

**Comment by super3** [comment]
Seems to be missing part of the license: 
http://opensource.org/licenses/MIT

**Comment by Gnewt** [comment]
Right, it's not the full license -- I only included the disclaimer since it's the "EULA" part i.e. the part that absolves the website operator of responsibility if something bad happens. If you'd like we can include the full license.

**Comment by super3** [comment]
Yeah I think that would be best to include the full one.

**Comment by Gnewt** [comment]
Alrighty, now it's the full license, and it appears under an expandable panel (like the FAQs on the homepage).

**Comment by super3** [comment]
Ack. Merge it.

**Pull request merged**
