### PR TITLE
changed the style of screenshots

### PR DESCRIPTION
**Pull request by ngbatnicdotmil**
changed the style of screenshots, so they look more similar to others, use ashampoo snap for for this kind of work

### CODE REVIEW

**Comment by super3** [comment]
Please squash.

**Comment by ngbatnicdotmil** [comment]
sorry, but I didn't get you, I don't understand

**Comment by super3** [comment]
Needs to be all in one commit not 3.

**Comment by ngbatnicdotmil** [comment]
I don't know how to do so, please help

**Comment by super3** [comment]
https://gun.io/blog/how-to-github-fork-branch-and-pull-request/

**Pull request closed without merging**
