### PR TITLE
some minor, some major

### PR DESCRIPTION
**Pull request by accessomat**
- state that wiki is an external link (as should most external links be)
- separate pools to dedicated pools and multicoin pools
- fix link from old /r/ppcoin to new /r/peercoin on resources page
- also added a section of online shops that accepts peercoin as payment to encourage more businesses to do so and support the businesses who does.
- add peer4commit as a way to get peercoins
- contribute is now a dropdown menu with links to the old volunteer form and
- a new page called participate that contains ways user may participate in the peercoin community

### CODE REVIEW

**Comment by super3** [comment]
Good stuff. Please squash.

**Comment by accessomat** [comment]
I think I ended up with 4 commits instead of 2 :P
I am trying to follow this guide
http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request
with no success.

Could you please direct to a better squash guide?

**Comment by super3** [comment]
https://gun.io/blog/how-to-github-fork-branch-and-pull-request/
or just close and create a new pull req with your changes in it.

**Comment by accessomat** [comment]
arrggghhhh.... i closed this pull request and opened a new one

**Pull request closed without merging**
