### PR TITLE
Update social icons in the header

### PR DESCRIPTION
**Pull request by brossi**
Added four social icons to the header and adjusted the respective styles across the different media queries.

Tested in Firefox, Chrome and Safari at different widths.

### CODE REVIEW

**Comment by super3** [comment]
ACK. Will fix bugs myself.

**Comment by brossi** [comment]
What did you run into?

**Comment by super3** [comment]
ACK as in 'acknowledgement.' Removed the "_blanks" and added the Youtube link. This has been pushed to the live site as of a few seconds ago.

**Comment by brossi** [comment]
All good then, thanks, Shawn.

When I've got a bit more time I'll prep transparent versions (or SVGs) of those icons, but for now, they should work fine.

Thanks for heading up that project

**Comment by pffff** [comment]
the twitter logo is the old twitter logo , see http://static4.businessinsider.com/image/4fcf9a1eeab8ea467c00000c-960/twitter-logo.jpg

**Pull request merged**
