### PR TITLE
add Chinese ZH-CN translate

### PR DESCRIPTION
**Pull request by kurokurokon**
first add translate for homepage and downloadpage  more are comming.

### CODE REVIEW

**Comment by super3** [comment]
Looks solid as far as I can tell. Need to figure that the best naming convention, and way to link to this.

**Comment by kurokurokon** [comment]
Just find "点点币"on Bter.com (one of the leading Chinese Market).
Maybe "股权币"  links to POS
"利息币"  links to Interest
"同等币" / "同辈币" links to Peer
"环保币" / “绿色币” links to eco friendly

Maybe something better

**Comment by kurokurokon** [comment]
Making a choice so I can just head for more pages.
A lot of pages are waiting for a translation.

**Comment by super3** [comment]
As per #54 I am going to install Fork CMS. This should provide us with the tools to easily handle translation.

**Pull request merged**
