### PR TITLE
Added a reCAPTCHA-protected contact form + Vircurex backup

### PR DESCRIPTION
**Pull request by Gnewt**
~~@super3, I sent you an email with the keyfile in it. I won't merge this request now -- you can after the keys file is in the right place. Also may be worth sending a test email (possibly with your email temporarily in place of sunny's) just to verify that mail() is working.~~

@super3, I added some 'smarter' behavior -- interview request link will default to mailto until the keyfile is copied in. Also, we now source some data from Vircurex if CMC is not playing nice.

### CODE REVIEW

**Comment by super3** [comment]
@Gnewt Hmmm. Do you think we could use your script to parse the entire Coinmarketcap site into JSON?

**Comment by Gnewt** [comment]
Yeah, pretty easily! For what?

**Comment by super3** [comment]
Wanted to build a stats website. Are you good with JS too?
https://github.com/super3/millib

**Comment by Gnewt** [comment]
I'm pretty good with JavaScript but not great at web design -- most of the JS I write is backend stuff, communicating with APIs etc. For millib, we could easily use BeautifulSoup or lxml to parse CoinMarketCap and use it as a source of data. millib is already written in Python it looks like; that's where I'm most comfortable.

**Comment by super3** [comment]
Probably want to restart the codebase. Eh, as long as you get it working I can get get the design part done. Want to talk via gchat or something?

**Comment by Gnewt** [comment]
Sure -- nick@nickmooney.me on gchat
I'm also always on Freenode and OFTC as Gnewt (more frequently on IRC than gchat).

**Pull request merged**
